"""empty message

Revision ID: 19124f48ad65
Revises: c19d7ae480ad
Create Date: 2023-05-12 10:06:56.409628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19124f48ad65'
down_revision = 'c19d7ae480ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
