"""empty message

Revision ID: 2a5b91d3c02d
Revises: 
Create Date: 2023-05-28 21:14:42.253123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5b91d3c02d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_id'), ['id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_id'), ['id'], unique=False)

    op.create_table('product_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productColorHex', sa.String(length=50), nullable=True),
    sa.Column('productColorName', sa.String(length=50), nullable=True),
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_color_id'), ['id'], unique=False)

    op.create_table('product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productSize', sa.String(length=10), nullable=True),
    sa.Column('productSizePrice', sa.String(length=100), nullable=True),
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productID'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_size_id'), ['id'], unique=False)

    op.create_table('transaction_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_item_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_item_id'))

    op.drop_table('transaction_item')
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_size_id'))

    op.drop_table('product_size')
    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_color_id'))

    op.drop_table('product_color')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_id'))

    op.drop_table('product')
    # ### end Alembic commands ###
