"""empty message

Revision ID: 5de830b92834
Revises: e8e5c251ef90
Create Date: 2023-05-11 11:52:51.460143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5de830b92834'
down_revision = 'e8e5c251ef90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorHex', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['colorHex'])
        batch_op.create_unique_constraint(None, ['colorName'])
        batch_op.drop_column('colorImage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorImage', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('colorHex')

    # ### end Alembic commands ###
