"""empty message

Revision ID: 7ea71a977d5f
Revises: 5de830b92834
Create Date: 2023-05-11 12:05:49.007659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ea71a977d5f'
down_revision = '5de830b92834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('colors')

    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.alter_column('colorName',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_index('colorHex')
        batch_op.drop_index('colorName')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('colorHex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorHex', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('colorName', ['colorName'], unique=False)
        batch_op.create_index('colorHex', ['colorHex'], unique=False)
        batch_op.alter_column('colorName',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('product_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
