"""empty message

Revision ID: d51fe2caf6fa
Revises: 1013c3d91423
Create Date: 2023-05-11 23:31:11.332789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd51fe2caf6fa'
down_revision = '1013c3d91423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=100), nullable=True))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
